# Notebook 1: Dataset Understanding

This notebook covers the foundational concepts required before starting any Machine Learning project. Each concept is explained with a definition, a real-world example, a Python implementation, output, interpretation, and its relevance to Machine Learning.

A sample dataset representing passenger records is used throughout this notebook to demonstrate each concept.

In [1]:
import pandas as pd
import numpy as np

data = {
    "PassengerId": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": ["John Smith", "Mary Jane", "Ali Khan", "Sara Lee", "Tom Brown",
             "Nina Rao", "Omar Ali", "Lucy Chen", "David Kim", "Anna Paul"],
    "Sex": ["male", "female", "male", "female", "male",
            "female", "male", "female", "male", "female"],
    "Age": [22, 38, 26, 35, 28, 4, 54, 2, 27, 14],
    "Pclass": [3, 1, 3, 1, 3, 2, 1, 3, 2, 3],
    "Fare": [7.25, 71.28, 7.92, 53.10, 8.05, 21.07, 51.86, 16.70, 13.00, 30.00],
    "Embarked": ["S", "C", "S", "S", "S", "S", "S", "S", "C", "Q"],
    "Survived": [0, 1, 1, 1, 0, 1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)
df

   PassengerId        Name     Sex  Age  Pclass   Fare Embarked  Survived
0            1  John Smith    male   22       3   7.25        S         0
1            2   Mary Jane  female   38       1  71.28        C         1
2            3    Ali Khan    male   26       3   7.92        S         1
3            4    Sara Lee  female   35       1  53.10        S         1
4            5   Tom Brown    male   28       3   8.05        S         0
5            6    Nina Rao  female    4       2  21.07        S         1
6            7    Omar Ali    male   54       1  51.86        S         0
7            8   Lucy Chen  female    2       3  16.70        S         1
8            9   David Kim    male   27       2  13.00        C         0
9           10   Anna Paul  female   14       3  30.00        Q         1

## 1. What is a Dataset?

### Concept
A dataset is a structured collection of data, usually arranged in rows and columns, where each row represents an observation (record) and each column represents a variable (feature).

### Example
A spreadsheet of passenger records with details such as name, age, and fare paid is a dataset.

### Implementation
See the code cell below.

In [2]:
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (10, 8)

   PassengerId        Name     Sex  Age  Pclass   Fare Embarked  Survived
0            1  John Smith    male   22       3   7.25        S         0
1            2   Mary Jane  female   38       1  71.28        C         1
2            3    Ali Khan    male   26       3   7.92        S         1
3            4    Sara Lee  female   35       1  53.10        S         1
4            5   Tom Brown    male   28       3   8.05        S         0

### Output
The dataset contains 10 rows and 8 columns, displayed above.

### Interpretation
Each row is one passenger record, and each column stores one attribute of that passenger.

### Insight
Before any analysis, it is necessary to know how the data is organized as rows and columns.

### AI/ML Relevance
Every Machine Learning model is trained on a dataset. Understanding its structure is the first step in any ML pipeline.

## 2. What is a Feature?

### Concept
A feature is an individual measurable property or column in a dataset, used as input for analysis or modeling.

### Example
Age, Fare, and Sex are features of a passenger.

### Implementation
See the code cell below.

In [3]:
features = df.columns.tolist()
print("Features:", features)

Features: ['PassengerId', 'Name', 'Sex', 'Age', 'Pclass', 'Fare', 'Embarked', 'Survived']

### Output
The list of all column names in the dataset is displayed above.

### Interpretation
Each item in this list represents one piece of information collected for every passenger.

### Insight
Features are the building blocks that a model uses to learn patterns.

### AI/ML Relevance
Feature selection and feature engineering directly affect model accuracy and performance.

## 3. What is a Target?

### Concept
The target is the column a model is trained to predict. It is also called the label or output variable.

### Example
Predicting whether a passenger survived (Survived column) based on other details.

### Implementation
See the code cell below.

In [4]:
target = df["Survived"]
target

0    0
1    1
2    1
3    1
4    0
5    1
6    0
7    1
8    0
9    1
Name: Survived, dtype: int64

### Output
The Survived column values are displayed above, containing 0 (did not survive) and 1 (survived).

### Interpretation
This column is what the model will learn to predict using the other features.

### Insight
Identifying the target correctly is essential before building any supervised learning model.

### AI/ML Relevance
Supervised learning algorithms require a clearly defined target to learn from labeled data.

## 4. Independent Variables

### Concept
Independent variables are the input features used to predict the target. Their values do not depend on other variables in the dataset.

### Example
Age, Sex, Fare, and Pclass are independent variables when predicting survival.

### Implementation
See the code cell below.

In [5]:
X = df.drop(columns=["Survived", "PassengerId", "Name"])
X.head()

      Sex  Age  Pclass   Fare Embarked
0    male   22       3   7.25        S
1  female   38       1  71.28        C
2    male   26       3   7.92        S
3  female   35       1  53.10        S
4    male   28       3   8.05        S

### Output
A table containing only the independent variables is displayed above.

### Interpretation
These columns act as the inputs supplied to a Machine Learning model.

### Insight
Identifier and text columns are usually excluded from independent variables unless processed further.

### AI/ML Relevance
Models learn the relationship between independent variables and the target to make predictions.

## 5. Dependent Variables

### Concept
The dependent variable is the outcome whose value depends on the independent variables. It is the same as the target variable.

### Example
Whether a passenger survived depends on factors such as age, class, and fare.

### Implementation
See the code cell below.

In [6]:
y = df["Survived"]
y

0    0
1    1
2    1
3    1
4    0
5    1
6    0
7    1
8    0
9    1
Name: Survived, dtype: int64

### Output
The dependent variable values are displayed above.

### Interpretation
This is the value the model tries to explain or predict using the independent variables.

### Insight
The dependent variable changes based on patterns present in the independent variables.

### AI/ML Relevance
The distinction between dependent and independent variables defines the supervised learning problem setup.

## 6. Numerical Features

### Concept
Numerical features contain numeric values that represent quantities and can be used directly in mathematical calculations.

### Example
Age and Fare are numerical features.

### Implementation
See the code cell below.

In [7]:
numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()
print("Numerical Features:", numerical_features)

Numerical Features: ['PassengerId', 'Age', 'Pclass', 'Fare', 'Survived']

### Output
The list of numerical columns is displayed above.

### Interpretation
These columns hold measurable, quantitative data.

### Insight
Numerical features often require scaling or normalization before being used in a model.

### AI/ML Relevance
Many algorithms perform mathematical operations directly on numerical features, making correct identification important.

## 7. Categorical Features

### Concept
Categorical features contain a limited set of distinct labels or categories rather than numeric quantities.

### Example
Sex and Embarked are categorical features.

### Implementation
See the code cell below.

In [8]:
categorical_features = df.select_dtypes(include=["object"]).columns.tolist()
print("Categorical Features:", categorical_features)

Categorical Features: ['Name', 'Sex', 'Embarked']

/tmp/ipykernel_514/3988148919.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(include=["object"]).columns.tolist()

### Output
The list of categorical columns is displayed above.

### Interpretation
These columns represent group membership rather than measurable quantities.

### Insight
Categorical features must be encoded into numeric form before most ML algorithms can use them.

### AI/ML Relevance
Encoding techniques such as one-hot encoding or label encoding are applied specifically to categorical features.

## 8. Discrete Features

### Concept
Discrete features take a countable, finite set of values, often whole numbers.

### Example
Pclass (1, 2, or 3) is a discrete feature.

### Implementation
See the code cell below.

In [9]:
print("Unique values in Pclass:", sorted(df["Pclass"].unique()))

Unique values in Pclass: [np.int64(1), np.int64(2), np.int64(3)]

### Output
The distinct values of Pclass are displayed above.

### Interpretation
Pclass only takes three fixed values, confirming it is discrete.

### Insight
Discrete features are often treated similarly to categorical features during modeling.

### AI/ML Relevance
Recognizing discrete features helps decide whether to treat a column as a category or a true numeric measure.

## 9. Continuous Features

### Concept
Continuous features can take any value within a range, including decimals, and are typically the result of measurement.

### Example
Fare and Age are continuous features.

### Implementation
See the code cell below.

In [10]:
print("Fare range:", df["Fare"].min(), "to", df["Fare"].max())

Fare range: 7.25 to 71.28

### Output
The minimum and maximum Fare values are displayed above.

### Interpretation
Fare can take any value within this range, including fractional amounts.

### Insight
Continuous features usually benefit from scaling and are well suited to statistical summaries.

### AI/ML Relevance
Continuous variables are commonly used directly in regression models and distance-based algorithms.

## 10. Identifier Columns

### Concept
Identifier columns uniquely identify each record and do not carry predictive information about the target.

### Example
PassengerId is an identifier column.

### Implementation
See the code cell below.

In [11]:
print("Unique PassengerId count:", df["PassengerId"].nunique())
print("Total rows:", len(df))

Unique PassengerId count: 10
Total rows: 10

### Output
The number of unique PassengerId values equals the total number of rows.

### Interpretation
Since every value is unique, PassengerId only identifies a row and has no relationship with survival.

### Insight
Identifier columns should generally be removed before training a model.

### AI/ML Relevance
Including identifier columns as features can mislead a model and cause poor generalization.

## 11. Target Variable

### Concept
The target variable is the specific column selected as the prediction goal of a supervised learning task.

### Example
In this dataset, Survived is selected as the target variable.

### Implementation
See the code cell below.

In [12]:
print("Target variable distribution:")
print(df["Survived"].value_counts())

Target variable distribution:
Survived
1    6
0    4
Name: count, dtype: int64

### Output
The count of each class (0 and 1) in the Survived column is displayed above.

### Interpretation
This shows how many passengers survived versus how many did not.

### Insight
Checking the balance of the target variable is important before model training.

### AI/ML Relevance
An imbalanced target variable can bias a model toward the majority class and requires special handling.

## 12. Metadata

### Concept
Metadata is data about the dataset itself, such as column names, data types, and memory usage, rather than the data values.

### Example
Knowing that Age is stored as an integer and Sex is stored as text is metadata.

### Implementation
See the code cell below.

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  10 non-null     int64
 1   Name         10 non-null     str
 2   Sex          10 non-null     str
 3   Age          10 non-null     int64
 4   Pclass       10 non-null     int64
 5   Fare         10 non-null     float64
 6   Embarked     10 non-null     str
 7   Survived     10 non-null     int64
dtypes: float64(1), int64(4), str(3)
memory usage: 772.0 bytes

### Output
Column names, data types, and non-null counts are displayed above.

### Interpretation
This summary describes the structure of the dataset rather than its actual content.

### Insight
Metadata helps identify data types and missing values before deeper analysis.

### AI/ML Relevance
Correct data types are required for preprocessing steps such as encoding and scaling.

## 13. Dataset Dimensions

### Concept
Dataset dimensions refer to the number of rows (observations) and columns (features) present in the dataset.

### Example
A dataset with 10 passengers and 8 attributes has dimensions of 10 rows by 8 columns.

### Implementation
See the code cell below.

In [14]:
rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 10
Number of columns: 8

### Output
The dataset dimensions are displayed above as rows and columns.

### Interpretation
This confirms the size of the dataset being analyzed.

### Insight
Dataset size influences which models and validation strategies are appropriate.

### AI/ML Relevance
Understanding dataset dimensions is necessary for planning memory usage, computation time, and train-test splitting.