# Notebook 1 – Dataset Understanding

## Load the Dataset

In [17]:
import pandas as pd
import os

# Automatically look for the dataset file in the current folder,
# trying a few common filenames for this dataset.
possible_names = ["healthcare_dataset.csv", "Healthcare_dataset.csv", "Healthcare Dataset.csv", "healthcare-dataset.csv"]
data_path = None

for name in possible_names:
    if os.path.exists(name):
        data_path = name
        break

if data_path is None:
    print("Could not find the dataset automatically.")
    print("Current folder:", os.getcwd())
    print("Files in this folder:", os.listdir())
    print("\nFix: set data_path manually below to the exact filename you see above,")
    print("e.g. data_path = 'my_actual_filename.csv'")
else:
    print("Found dataset at:", data_path)

# If the automatic search above didn't find it, uncomment and edit the line below:
# data_path = "PUT_YOUR_EXACT_FILENAME_HERE.csv"

df = pd.read_csv(data_path)
df.head()

Found dataset at: healthcare_dataset.csv

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## Dataset Documentation

**Dataset name:** Healthcare Dataset

**Dataset source:** Kaggle — [Healthcare Dataset by prasad22](https://www.kaggle.com/datasets/prasad22/healthcare-dataset)

**Business/domain:** Healthcare — patient admission records from a hospital system, covering demographics, medical conditions, admission/discharge details, billing, and test outcomes.

**Number of rows and columns:** see the code cell below for the exact counts.

**Meaning of important columns:**
- `Name` — patient's name (identifier-like, not useful for analysis).
- `Age` — patient's age in years (numerical).
- `Gender` — patient's gender (categorical).
- `Blood Type` — patient's blood group, e.g. A+, O- (categorical).
- `Medical Condition` — diagnosed condition, e.g. Diabetes, Cancer (categorical).
- `Date of Admission` — the date the patient was admitted (date/time).
- `Doctor` — attending doctor's name (identifier-like).
- `Hospital` — hospital/facility name (categorical/identifier-like).
- `Insurance Provider` — insurance company covering the patient (categorical).
- `Billing Amount` — amount billed for the stay (numerical, continuous).
- `Room Number` — assigned room number (numerical, but functions as an identifier rather than a measurable quantity).
- `Admission Type` — Emergency, Elective, or Urgent (categorical).
- `Discharge Date` — the date the patient was discharged (date/time).
- `Medication` — medication prescribed (categorical).
- `Test Results` — Normal, Abnormal, or Inconclusive (categorical).

**Target variable:** `Test Results` is used as the target variable in this project — predicting whether a patient's test outcome is Normal, Abnormal, or Inconclusive based on their other attributes. (`Medical Condition` is a reasonable alternative target.)

**Why this dataset was selected:** It combines a realistic mix of numerical, categorical, and date/time columns, has a large enough number of records for meaningful analysis, and includes real-world data-quality issues (such as inconsistent text casing in names and duplicate-like records) that make it suitable for practicing data inspection and cleaning.

In [18]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 55500
Number of Columns: 15

## What is a Dataset?

### Concept
A dataset is an organized collection of data, typically structured as a table where each row is an observation and each column is an attribute of that observation.

### Example
This healthcare dataset is a table where each row represents one patient's hospital admission record.

### Implementation
See the code cell below.

In [19]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

### Interpretation
Each row is a single, self-contained observation (one patient's admission), and each column describes one property of that observation.

## What is a Feature?

### Concept
A feature (also called a variable or attribute) is any column in the dataset that describes a characteristic of an observation.

### Example
`Age`, `Gender`, and `Billing Amount` are all features of a patient's record.

### Implementation
See the code cell below.

In [20]:
print("Features:", df.columns.tolist())

Features: ['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']

### Interpretation
Every column apart from the target (if one is used for prediction) can serve as an input feature for analysis or modeling.

## What is a Target?

### Concept
The target (or label) is the specific column a predictive model tries to estimate or classify, based on the other features.

### Example
In this dataset, `Test Results` is treated as the target — the outcome we would want to predict.

### Implementation
See the code cell below.

In [21]:
print(df["Test Results"].value_counts())

Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64

### Interpretation
The target column has a small number of distinct classes (Normal, Abnormal, Inconclusive), which makes it suitable for a classification task.

## Independent Variables

### Concept
Independent variables are the input features used to predict or explain the target; their values are not influenced by the target.

### Example
`Age`, `Gender`, `Medical Condition`, `Admission Type`, and `Billing Amount` are independent variables with respect to `Test Results`.

### Implementation
See the code cell below.

In [22]:
independent_vars = [col for col in df.columns if col != "Test Results"]
print("Independent Variables:", independent_vars)

Independent Variables: ['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication']

### Interpretation
These are the columns that would be fed into a model to make a prediction about the target.

## Dependent Variables

### Concept
The dependent variable is the outcome that depends on (and is predicted from) the independent variables. It is another name for the target.

### Example
`Test Results` is the dependent variable in this dataset.

### Implementation
See the code cell below.

In [23]:
dependent_var = "Test Results"
print("Dependent Variable:", dependent_var)

Dependent Variable: Test Results

### Interpretation
Its value is assumed to change in response to the combination of independent variables describing each patient.

## Numerical Features

### Concept
Numerical features contain measurable quantities and support mathematical operations like averaging or comparison.

### Example
`Age` and `Billing Amount` are numerical features.

### Implementation
See the code cell below.

In [24]:
numerical_features = df.select_dtypes(include="number").columns.tolist()
print("Numerical Features:", numerical_features)

Numerical Features: ['Age', 'Billing Amount', 'Room Number']

### Interpretation
These columns can be summarized with statistics like mean, median, and standard deviation.

## Categorical Features

### Concept
Categorical features contain a limited set of distinct labels or categories rather than numeric quantities.

### Example
`Gender`, `Blood Type`, and `Insurance Provider` are categorical features.

### Implementation
See the code cell below.

In [25]:
categorical_features = df.select_dtypes(include="object").columns.tolist()
print("Categorical Features:", categorical_features)

Categorical Features: ['Name', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']

C:\Users\sibyr\AppData\Local\Temp\ipykernel_24360\781928268.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(include="object").columns.tolist()

### Interpretation
These columns represent group membership rather than measurable quantities, and are best summarized with counts or proportions.

## Discrete Features

### Concept
Discrete features take on a countable, finite (or countably infinite) set of values — often whole numbers.

### Example
`Room Number` is discrete — rooms are assigned whole numbers with no meaningful values in between.

### Implementation
See the code cell below.

In [26]:
print("Unique Room Numbers:", df["Room Number"].nunique())
print(df["Room Number"].unique()[:10])

Unique Room Numbers: 400
[328 265 205 450 458 389 277 316 249 394]

### Interpretation
Room numbers are counted, not measured — there is no meaningful "half room," which is the hallmark of a discrete variable.

## Continuous Features

### Concept
Continuous features can take any value within a range, including fractional or decimal values.

### Example
`Billing Amount` is continuous — it can take any decimal value within a range.

### Implementation
See the code cell below.

In [27]:
print(df["Billing Amount"].describe())

count    55500.000000
mean     25539.316097
std      14211.454431
min      -2008.492140
25%      13241.224652
50%      25538.069376
75%      37820.508436
max      52764.276736
Name: Billing Amount, dtype: float64

### Interpretation
Billing amounts vary smoothly across a wide numeric range, unlike the fixed, countable values seen in discrete features.

## Identifier Columns

### Concept
Identifier columns uniquely (or near-uniquely) label each record and are not useful as predictive features.

### Example
`Name` and `Doctor` act as identifiers rather than predictive features.

### Implementation
See the code cell below.

In [28]:
print("Unique Names:", df["Name"].nunique(), "out of", len(df), "rows")
print("Unique Doctors:", df["Doctor"].nunique())

Unique Names: 49992 out of 55500 rows
Unique Doctors: 40341

### Interpretation
A high ratio of unique values to total rows signals that a column is functioning as an identifier rather than a meaningful predictive feature.

## Target Variable

### Concept
The target variable is the specific column selected as the prediction goal for this project.

### Example
`Test Results` — classifying whether a patient's test outcome is Normal, Abnormal, or Inconclusive.

### Implementation
See the code cell below.

In [29]:
df["Test Results"].value_counts(normalize=True)

Test Results
Abnormal        0.335622
Normal          0.333640
Inconclusive    0.330739
Name: proportion, dtype: float64

### Interpretation
Viewing the proportions shows whether the classes are balanced or skewed, which matters for later modeling choices.

## Metadata

### Concept
Metadata is "data about data" — information describing the dataset itself, such as column names, data types, and source, rather than the observations.

### Example
The dataset documentation section above (name, source, domain, column meanings) is metadata.

### Implementation
See the code cell below.

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 12.3 MB

### Interpretation
`info()` is a convenient way to view key metadata: column names, data types, and non-null counts, all in one place.

## Dataset Dimensions

### Concept
Dataset dimensions refer to its size, expressed as the number of rows (observations) and columns (features).

### Example
This dataset's dimensions are printed below.

### Implementation
See the code cell below.

In [31]:
print("Dataset Dimensions (rows, columns):", df.shape)

Dataset Dimensions (rows, columns): (55500, 15)

### Interpretation
Knowing the dimensions upfront helps gauge whether the dataset is large enough for reliable analysis and what computational approach is feasible.